# Generated by Django 4.1.2 on 2022-10-26 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('c_type', models.CharField(choices=[('D', 'Dusting'), ('V', 'Vacuuming'), ('B', 'Dusting & Vacuuming')], default='B', max_length=1)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.widget')),
            ],
        ),
    ]
