# Generated by Django 4.1.2 on 2022-10-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('function', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cleaning',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='c_type',
            field=models.CharField(choices=[('D', 'Dusting'), ('V', 'Vacuuming'), ('B', 'Dusting & Vacuuming')], default='B', max_length=1, verbose_name='cleaning type'),
        ),
    ]
