# Generated by Django 4.1.2 on 2022-10-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accessory_alter_cleaning_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
